### PR TITLE
Smartphone Brands Analysis

### PR DESCRIPTION
**Pull request by p1utoze**
# Pull Request for ML-Crate 💡

## Issue Title: Smartphone Brands Analysis #399 

- **Info about the related issue (Aim of the project)** :  Create a exploratory data analysis project which analyses different mobile brands.
- **Name:**  Adithya Awati
- **GitHub ID:**  p1utoze
- **Idenitfy yourself:**  I'm a sophomore participating in kWoC22

Closes: #399 

### Describe the add-ons or changes you've made 📃

folders added: Model, Images, Dataset
files added: readme.md, requirement.txt 

## Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested: Tested on PyCharm and Jupyter Lab
Describe how have you verified the changes made: Code executes without errors

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Why have you added Amazon Books Analysis files? Just add the Smartphone Brands Analysis project's files.
@p1utoze

**Comment by p1utoze** [comment]
My bad I removed the file you mentioned now.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please remove the `.idea` folder.

**Comment by p1utoze** [comment]
Removed the .idea folder files.

**Review by abhisheks008 — APPROVED** [review]
Picture perfect. Really impressive work, your PR is approved and ready to be merged.
@p1utoze

**Pull request merged**
